image:
  repository: 123456789012.dkr.ecr.ap-southeast-3.amazonaws.com/project-repository/project
  pullPolicy: Always
  tag: "dev-14"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
