apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-prod
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/instance: project-prod
spec:
  project: project

  sources:
    - repoURL: registry.internal.corp/project
      chart: project
      targetRevision: "2.0.1"
      helm:
        valueFiles:
          - $values/gitops/values/prod/values.yaml

    - repoURL: git@gitlab.internal.corp:devops/gitops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: project-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
